version: 2
sources:
  - name: dagster_example_catalog
    schema: dagster_example_catalog
    config:
      plugin: iceberg
      iceberg_table: "air_quality.{identifier}"
    tables:
      - name: daily_air_quality_data
        # Link to the source asset so that Dagster knows what to do with this data
        #  See: https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/upstream-assets#step-3-in-the-dbt-project-replace-a-seed-with-a-source
        meta:
          dagster:
            asset_key: ["daily_air_quality_data"]
