services:
  dagster-pyiceberg-example:
    build:
      dockerfile: Dockerfile
      context: "."
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/home/vscode/workspace:cached
    network_mode: service:pyiceberg-catalog-db
    # depends_on:
    #   - app
    # networks:
    #   - network
  pyiceberg-catalog-db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pyiceberg
      POSTGRES_DB: catalog
      POSTGRES_PASSWORD: pyiceberg

volumes:
  postgres-data:
